services:
  db:
    image: postgres:15
    container_name: shopla_postgres
    restart: always
    environment:
      POSTGRES_USER: shopla_user
      POSTGRES_PASSWORD: shopla_password
      POSTGRES_DB: shopla_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: shopla_redis
    restart: always
    ports:
      - "6379:6379"

  api:
    build: .
    container_name: shopla_api
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./uploads:/app/uploads
    environment:
      - DATABASE_URL=postgresql+asyncpg://shopla_user:shopla_password@db:5432/shopla_db
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
